from PIL import Image
from BilliardsDistinguish.ImageProcess import *

def createtemplateBalls():
    im0 = Image.new( "RGB", ( 640, 640 ), color = "rgb(255,255,255)" )
    im0 = addEllipseMask( im0 )
    im0.save( "../input/0.jpg" )
    drawEllipseHistogram( im0 ).save( "../input/0_histogram.jpg" )
    drawEllipseHistogram( im0.convert( "L" ) ).save( "../input/0_bright_histogram.jpg" )

    im1 = Image.new( "RGB", ( 640, 640 ), color = "rgb(255,255,0)" )
    im1 = addEllipseMask( im1 )
    im1.save( "../input/1.jpg" )
    drawEllipseHistogram( im1 ).save( "../input/1_histogram.jpg" )
    drawEllipseHistogram( im1.convert( "L" ) ).save( "../input/1_bright_histogram.jpg" )
    draw = ImageDraw.Draw( im1, mode = "RGB" )
    draw.ellipse( ( 90, 90, 512, 512 ), fill = "rgb(255,255,255)" )
    im1.save( "../input/9.jpg" )
    drawEllipseHistogram( im1 ).save( "../input/9_histogram.jpg" )
    drawEllipseHistogram( im1.convert( "L" ) ).save( "../input/9_bright_histogram.jpg" )

    im2 = Image.new( "RGB", ( 640, 640 ), color = "rgb(0,0,255)" )
    im2 = addEllipseMask( im2 )
    im2.save( "../input/2.jpg" )
    drawEllipseHistogram( im2 ).save( "../input/2_histogram.jpg" )
    drawEllipseHistogram( im2.convert( "L" ) ).save( "../input/2_bright_histogram.jpg" )
    draw = ImageDraw.Draw( im2, mode = "RGB" )
    draw.ellipse( ( 90, 90, 512, 512 ), fill = "rgb(255,255,255)" )
    im2.save( "../input/10.jpg" )
    drawEllipseHistogram( im2 ).save( "../input/10_histogram.jpg" )
    drawEllipseHistogram( im2.convert( "L" ) ).save( "../input/10_bright_histogram.jpg" )

    im3 = Image.new( "RGB", ( 640, 640 ), color = "rgb(255,0,0)" )
    im3 = addEllipseMask( im3 )
    im3.save( "../input/3.jpg" )
    drawEllipseHistogram( im3 ).save( "../input/3_histogram.jpg" )
    drawEllipseHistogram( im3.convert( "L" ) ).save( "../input/3_bright_histogram.jpg" )
    draw = ImageDraw.Draw( im3, mode = "RGB" )
    draw.ellipse( ( 90, 90, 512, 512 ), fill = "rgb(255,255,255)" )
    im3.save( "../input/11.jpg" )
    drawEllipseHistogram( im3 ).save( "../input/11_histogram.jpg" )
    drawEllipseHistogram( im3.convert( "L" ) ).save( "../input/11_bright_histogram.jpg" )

    im4 = Image.new( "RGB", ( 640, 640 ), color = "rgb(200,0,200)" )
    im4 = addEllipseMask( im4 )
    im4.save( "../input/4.jpg" )
    drawEllipseHistogram( im4 ).save( "../input/4_histogram.jpg" )
    drawEllipseHistogram( im4.convert( "L" ) ).save( "../input/4_bright_histogram.jpg" )
    draw = ImageDraw.Draw( im4, mode = "RGB" )
    draw.ellipse( ( 90, 90, 512, 512 ), fill = "rgb(255,255,255)" )
    im4.save( "../input/12.jpg" )
    drawEllipseHistogram( im4 ).save( "../input/12_histogram.jpg" )
    drawEllipseHistogram( im4.convert( "L" ) ).save( "../input/12_bright_histogram.jpg" )

    im5 = Image.new( "RGB", ( 640, 640 ), color = "rgb(255,128,0)" )
    im5 = addEllipseMask( im5 )
    im5.save( "../input/5.jpg" )
    drawEllipseHistogram( im5 ).save( "../input/5_histogram.jpg" )
    drawEllipseHistogram( im5.convert( "L" ) ).save( "../input/5_bright_histogram.jpg" )
    draw = ImageDraw.Draw( im5, mode = "RGB" )
    draw.ellipse( ( 90, 90, 512, 512 ), fill = "rgb(255,255,255)" )
    im5.save( "../input/13.jpg" )
    drawEllipseHistogram( im5 ).save( "../input/13_histogram.jpg" )
    drawEllipseHistogram( im5.convert( "L" ) ).save( "../input/13_bright_histogram.jpg" )

    im6 = Image.new( "RGB", ( 640, 640 ), color = "rgb(0,255,0)" )
    im6 = addEllipseMask( im6 )
    im6.save( "../input/6.jpg" )
    drawEllipseHistogram( im6 ).save( "../input/6_histogram.jpg" )
    drawEllipseHistogram( im6.convert( "L" ) ).save( "../input/6_bright_histogram.jpg" )
    draw = ImageDraw.Draw( im6, mode = "RGB" )
    draw.ellipse( ( 90, 90, 512, 512 ), fill = "rgb(255,255,255)" )
    im6.save( "../input/14.jpg" )
    drawEllipseHistogram( im6 ).save( "../input/14_histogram.jpg" )
    drawEllipseHistogram( im6.convert( "L" ) ).save( "../input/14_bright_histogram.jpg" )

    im7 = Image.new( "RGB", ( 640, 640 ), color = "rgb(128,0,0)" )
    im7 = addEllipseMask( im7 )
    im7.save( "../input/7.jpg" )
    drawEllipseHistogram( im7 ).save( "../input/7_histogram.jpg" )
    drawEllipseHistogram( im7.convert( "L" ) ).save( "../input/7_bright_histogram.jpg" )
    draw = ImageDraw.Draw( im7, mode = "RGB" )
    draw.ellipse( ( 90, 90, 512, 512 ), fill = "rgb(255,255,255)" )
    im7.save( "../input/15.jpg" )
    drawEllipseHistogram( im7 ).save( "../input/15_histogram.jpg" )
    drawEllipseHistogram( im7.convert( "L" ) ).save( "../input/15_bright_histogram.jpg" )

    im8 = Image.new( "RGB", ( 640, 640 ), color = "rgb(0,0,0)" )
    im8 = addEllipseMask( im8 )
    im8.save( "../input/8.jpg" )
    drawEllipseHistogram( im8 ).save( "../input/8_histogram.jpg" )
    drawEllipseHistogram( im8.convert( "L" ) ).save( "../input/8_bright_histogram.jpg" )


if __name__ == "__main__":
    im = Image.open( "../input/_9.jpg" )
    im = im.filter( ImageFilter.SMOOTH_MORE ).filter( ImageFilter.SMOOTH_MORE )
    x, y, w, h = locateEllipseInImage( im )
    im = cutImage( im, x, y, w, h )
    im.save( "../input/_9_cut.jpg" )
    im = addEllipseMask( im )
    im.save( "../input/_9_cut_mask.jpg" )
    imHistogramRGB = drawEllipseHistogram( im )
    imHistogramRGB.save( "../input/_9_histogram.jpg" )
    imHistogramBright = drawEllipseHistogram( im.convert( "L" ) )
    imHistogramBright.save( "../input/_9_bright_histogram.jpg" )
